repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-docstring-first
    -   id: detect-private-key
    -   id: name-tests-test
        args: [--pytest-test-first]

-   repo: local
    hooks:
    -   id: black
        name: black
        entry: poetry run black src tests
        language: system
        types: [python]

    -   id: ruff
        name: ruff
        entry: poetry run ruff -n --fix .
        always_run: true
        language: system

    -   id: pytest
        name: pytest
        entry: poetry run pytest
        pass_filenames: false
        always_run: true
        language: system
